#!/usr/bin/env bash

function installcask() {
    if brew cask info "${@}" | grep "Not installed" > /dev/null; then
        brew cask install "${@}"
    else
        echo "Warning: ${@} already installed"
    fi
}


## Update Homebrew and installed formulae

# Make sure we’re using the latest Homebrew
brew update
# Upgrade any already-installed formulae
brew upgrade
# Install cask brew extrenal command
brew tap phinze/homebrew-cask
brew install brew-cask


## Install common CLI tools:

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils
# Install `rename` command
brew install rename
# Install `tree` command
brew install tree
# Install `pkill`, `pgrep` and `pfind`
brew install proctools
# Install wget with IRI support
brew install wget --enable-iri


## Install shells

brew install bash
brew install fish


## Install devel tools

brew install git
brew install postgresql
brew install node
brew install nmap
brew install the_silver_searcher

# Applications

installcask google-chrome
installcask firefox
installcask tor-browser
installcask iterm2
installcask emacs
installcask macvim
installcask the-unarchiver
installcask transmission
installcask virtualbox
installcask vlc
installcask alfred
installcask clementine
installcask f-lux
installcask lime-chat
installcask adium
installcask skype
installcask dropbox
installcask optimal-layout
installcask opera
installcask libre-office
installcask diffmerge
installcask sourcetree


# Remove outdated versions from the cellar
brew cleanup


# Print notes
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."
