#!/usr/bin/env bash


## Update Homebrew and installed formulae

# Make sure we’re using the latest Homebrew
brew update
# Upgrade any already-installed formulae
brew upgrade
# Install cask brew extrenal command
brew tap phinze/homebrew-cask
brew install brew-cask


## Install common CLI tools:

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils
# Install `rename` command
brew install rename
# Install `tree` command
brew install tree
# Install `pkill`, `pgrep` and `pfind`
brew install proctools
# Install `wget` with IRI support
brew install wget --enable-iri
# Install `ag` command
brew install the_silver_searcher
# Install `nmap` command
brew install nmap


## Install shells

brew install bash
brew install fish


## Install devel tools

# Version control
brew install git
# Databases
brew install postgresql
# Node
brew install node
# OCAML
brew install ocaml
brew install ocaml-pcre
brew install opam


## Applications casks

function installcask() {
    if brew cask info "${@}" | grep "Not installed" > /dev/null; then
        brew cask install "${@}"
    else
        echo "Warning: ${@} already installed"
    fi
}

# Web browsers
installcask google-chrome
installcask firefox
installcask opera
installcask tor-browser
# Terms
installcask iterm2
# Editors / Word processors
installcask emacs
installcask macvim
installcask libre-office
# Devel tools
installcask virtualbox
installcask diffmerge
installcask sourcetree
# Chat
installcask lime-chat
installcask adium
installcask skype
# Download / Share
installcask transmission
installcask dropbox
# Media
installcask vlc
installcask clementine
# File utils
installcask the-unarchiver
# Desktop utils
installcask optimal-layout
installcask alfred
# Misc
installcask f-lux


## Cleanup

# Remove outdated versions from the cellar
brew cleanup
# Print notes
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."
